version: '3'

services:
  nginx:
    build: .
    container_name: nginx_web
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/Users/kelvin/Documents/Belajar-CICD/Apps-nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - "/Users/kelvin/Documents/Belajar-CICD/Apps-nginx:/project"
#      - "/Users/kelvin/Documents/Belajar-CICD/Apps-nginx/entrypoint.sh:/root/entrypoint.sh"
#   entrypoint: sh /root/entrypoint.sh